language: node_js
node_js:
    - "4"
    - "6"

addons:
  apt:
    packages:
    - ldap-utils
    - slapd

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run coverage
    - ./node_modules/.bin/codecov
    - grunt eslint:test

sudo: false
